language: ruby
script: "bundle exec rake test"
rvm:
  - 2.0.0
  - 2.1.8
  - 2.2.4
  - 2.3.0
  - ruby-head

gemfile:
  - gemfiles/activerecord_40_pg_017.gemfile
  - gemfiles/activerecord_40_pg_018.gemfile
  - gemfiles/activerecord_41_pg_017.gemfile
  - gemfiles/activerecord_41_pg_018.gemfile
  - gemfiles/activerecord_42_pg_017.gemfile
  - gemfiles/activerecord_42_pg_018.gemfile
  - gemfiles/activerecord_50_pg_018.gemfile
  - gemfiles/activerecord_51_pg_020.gemfile

services:
  - postgresql

before_script:
  - cp test/database.yml.sample test/database.yml
  - psql -c 'create database pg_ltree_test;' -U postgres

matrix:
  allow_failures:
    - rvm: ruby-head
  exclude:
    - rvm: 2.0.0
      gemfile: gemfiles/activerecord_50_pg_018.gemfile
    - rvm: 2.1.8
      gemfile: gemfiles/activerecord_50_pg_018.gemfile
